### ISSUE TITLE
Sign-up page does not work

### ISSUE THREAD

**Issue by paulrd** [walkable-server/realworld-fulcro#7]
After exectuting lein repl, (dev), (go) and connecting to localhost:3000/index.html (or localhhost:4000 with caddy), when I click on the sign-up page link at top-right, no sign-up form is displayed.

**Comment by myguidingstar** [comment]
somehow I got no notification for this issue. You can join #walkable channel on slack or zulip.
That's strange, I have it works normally.
If you can see the link, then cljs has been compiled and run because there's almost no html, just fulcro renders the whole app.
Can you open fulcro inspect tool to look around?
